#!/bin/sh

case ${ENV_TYPE:-development} in

production)
  node server
  ;;

development)
  # Watch src for changes and build with babel
  # Skip initial build because the image already contains compiled src
  cd $SRC_DIR
  babel --watch --quiet --skip-initial-build \
    --ignore node_modules --retain-lines --source-maps inline \
    --copy-files --out-dir $RUN_DIR \
    $SRC_DIR &

  cd $RUN_DIR

  NODEMON_WATCH_DIRS="-w lib -w server -w db -w config.js"

  # Run auth server
  nodemon --quiet --delay 0.5 \
    $NODEMON_WATCH_DIRS \
    --exec node server &

  # Run tests
  nodemon --quiet --delay 0.5 \
    $NODEMON_WATCH_DIRS \
    --exec devops/test &

  wait
  ;;
esac
